[package]
name = "uu_grep"
description = "A Rust implementation of GNU Grep"
repository = "https://github.com/uutils/grep"
edition = "2024"
rust-version = "1.88.0"
version = "0.2.0"
license = "MIT"
homepage = "https://github.com/uutils/grep"
keywords = ["grep", "uutils", "cross-platform", "cli", "utility"]
categories = ["command-line-utilities"]

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-{ target }{ archive-suffix }"
bin-dir = "{ bin }{ binary-ext }"
pkg-fmt = "txz"

[package.metadata.binstall.overrides.x86_64-pc-windows-msvc]
pkg-fmt = "zip"

[[bin]]
name = "grep"
path = "src/main.rs"

[lib]
name = "uu_grep"
path = "src/lib.rs"

[dependencies]
clap = { version = "4.5", features = ["wrap_help", "cargo", "color"] }
glob = "0.3.1"
fancy-regex = { version = "0.19.2", default-features = false, features = ["std", "unicode"] }
memchr = "2.7.2"
uucore = { git = "https://github.com/wtcpython/coreutils.git", branch = "uucore-regex", features = ["regex"] }
walkdir = "2.5"

[[bench]]
name = "grep_bench"
harness = false

[dev-dependencies]
criterion = { version = "5.0.0", package = "codspeed-criterion-compat" }
uutests = "0.12.0"

[profile.dist]
inherits = "release"
lto = "fat"
